### ISSUE TITLE
Zero OS OpenRPC Document generation from v (using python now)

### ISSUE THREAD

**Issue by timurgordon** [crystaluniverse/crystallib#238]
## todo

* [ ] generate openrpc specs starting from V files
* [ ] test openrpc files in playground
* [ ] host playground in vweb server (make function for it), put files in weblibs as needed
* [ ] mechanism to generate v client
* [ ] mechanism to generate v server (with methods not filled in)
* [ ] mechanism to generate go client (so we can easily use in zos)
* [ ] mechanism to generate go server (with methods not filled in)
* [ ] make end2end example, where a client talks to a mycelium based server

## implementation remarks

* openrpc messages send over sockets, websockets or mycelium messages
* for server: use co-routines (see research coroutines for example)
* see https://github.com/freeflowuniverse/crystallib/issues/290

## test on zos

The goal is to use the openrpc document generator to generate openrpc specifications for exposed ZeroOS primitives

**Comment by timurgordon** [comment]
Progress with commit 7ee672babee082e4a9a5751cff94861733829dc6. Currently document generation works. The client methods remain as prototypes to build the document from, but can be filled in.

**Comment by timurgordon** [comment]
This issue remains to be verified after the development of a OpenRPC Handler for ZOS primitives. Before then the created module should be moved from research to crystallib, and an OpenRPC playground example using the generated OpenRPC document should be provided.

**Comment by despiegk** [comment]
see https://github.com/freeflowuniverse/crystallib/issues/290

**Comment by despiegk** [comment]
see hero repo
